[menu]
[[menu.footer]]
    identifier = 'home'
    name = 'Home'
    url = '/home/'
    pre = "<div class='nav-link'>"
    post = "</div>"
    weight = 1
[[menu.footer]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    pre = "<div class='nav-link'>"
    post = "</div>"
    weight = 2 
[[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy Policy'
    url = '/policy/'
    pre = "<div class='nav-link'>"
    post = "</div>"
    weight = 3 
[params]
    subtitle_description = "Add a subtitle_description variable to your params to update this"
