[menu]
[[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    pre = "<div class='nav-link'>"
    post = "</div>"
    url = '/content/'
    weight = 1
[[menu.main]]
    identifier= 'tags'
    name = 'Tags'
    pre = "<div class='nav-link'>"
    url = '/tags/'
    post = "</div>"
    weight =2
[[menu.main]]
    identifier = 'about'
    name = 'About'
    pre = "<div class='nav-link'>"
    url = '/about/'
    post = "</div>"
    weight = 2
[[menu.main]]
    identifier = 'github'
    name = ''
    pre = "<div class='header-icon nav-link'><img class='text-white' src='/svg/github.svg' alt='test'/>"
    url = 'https://github.com'
    post = "</div>"
    weight = 3
[[menu.main]]
    identifier = 'twitter'
    name = ''
    url = 'https://twitter.com'
    pre = "<div class='header-icon nav-link'><img class='text-white' src='/svg/twitter.svg' alt='test'/>"
    post = "</div>"
    weight = 4 
[[menu.main]]
    identifier = 'linked-in'
    name = ''
    url = "https://www.linkedin.com"
    pre = "<div class='header-icon nav-link'><img src='/svg/linkedin.svg' alt='test'/>"
    post = "</div>"
    weight = 5 
[[menu.main]]
    identifier = 'facebook'
    name = ''
    url = "https://www.facebook.com"
    pre = "<div class='header-icon nav-link'><img src='/svg/facebook.svg' alt='test'/>"
    post = "</div>"
    weight = 6 
[[menu.main]]
    identifier = 'instagram'
    name = ''
    url = "https://www.instagram.com"
    pre = "<div class='header-icon nav-link'><img src='/svg/instagram.svg' alt='test'/>"
    post = "</div>"
    weight = 6 
[[menu.footer]]
    identifier = 'home'
    name = 'Home'
    url = '/home/'
    pre = "<div class='nav-link'>"
    post = "</div>"
    weight = 1
[[menu.footer]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    pre = "<div class='nav-link'>"
    post = "</div>"
    weight = 2 
[[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy Policy'
    url = '/policy/'
    pre = "<div class='nav-link'>"
    post = "</div>"
    weight = 3 
[params]
    subtitle_description = "Add a subtitle_description variable to your params to update this"
